# version: '3'

services:
  app:
    build: .
    container_name: heyshop-app
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ajuda o hot-reload no Docker
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: heyshop-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=prismaapi
